services:
  db:
    image: postgres:16
    container_name: db
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network

  dbt:
    build:
      context: ./
    container_name: dbt
    env_file:
      - ./datawarehouse/profiles/.env
    environment:
      DBT_PROFILES_DIR: /PROJECT/datawarehouse/profiles
      DBT_PROJECT_DIR: /PROJECT/datawarehouse
      DB_HOST: ${DB_HOST_CONTAINER}
    volumes:
      - ./datawarehouse:/PROJECT/datawarehouse
    networks:
      - db-network
    depends_on:
      - db

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: always
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "5050:80"
    volumes:
    - pgadmin-cache:/var/lib/pgadmin
    networks:
      - db-network
    depends_on:
      - db

volumes:
  db-data:
    driver: local
  pgadmin-cache:
    driver: local

networks:
  db-network:
    driver: bridge