version: "3.1"

services:
  scheduler:
    mem_limit: 1g
    cpus: 0.5
    user: "${UID}:${GID}"
    env_file:
      - ./.env
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${DB_URL}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${DB_URL}
      AIRFLOW__CORE__LOAD_EXAMPLES: False
    volumes:
      - ./datawarehouse:/usr/local/airflow/datawarehouse
    networks:
      - project_net

  postgres:
    container_name: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: False
    networks:
      - project_net

  triggerer:
    mem_limit: 1g
    cpus: 0.5
    user: "${UID}:${GID}"
    env_file:
      - ./.env
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${DB_URL}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${DB_URL}
      AIRFLOW__CORE__LOAD_EXAMPLES: False
    volumes:
      - ./datawarehouse:/usr/local/airflow/datawarehouse
    networks:
      - project_net

  webserver:
    mem_limit: 1g
    cpus: 0.5
    env_file:
      - ./.env
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${DB_URL}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${DB_URL}
      AIRFLOW__CORE__LOAD_EXAMPLES: False
    networks:
      - project_net

  pgadmin:
    image: elestio/pgadmin:REL-8_12
    container_name: pgadmin
    restart: always
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "5050:80"
    volumes:
    - pgadmin-cache:/var/lib/pgadmin
    networks:
      - project_net

  api_app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.api_app
    container_name: api_app
    restart: always
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/api:/datawarehouse:/app
    volumes:
      - ./api:/api
      - ./datawarehouse/sources:/datawarehouse/sources
      - ./app:/app
    ports:
    - "8200:8200"
    - "8210:8210"
    networks:
      - project_net
    command: "sh ./execute.sh"

volumes:
  pgadmin-cache:

networks:
  project_net: