version: 2

sources:
  - name: WebScraping
    schema: data
    tables:
      - name: stg-mercado_livre_tenis_corrida_masculino
        description: "Staging table with masculine running shoes from Mercado Livre"
        columns:
          - name: brand
            description: "Shoes brand"
          - name: name
            description: "Shoes name"
            tests:
              - unique
              - not_null

          - name: old_price
            description: "Shoes old price"
          - name: new_price
            description: "Shoes new price"
          - name: reviews_rating_number
            description: "Number of stars that the customers gave to the product"
          - name: reviews_amount
            description: "Number of reviews made by customers"
          - name: datetime
            description: "The date and time when the crawler obtained the shoes information"

      - name: stg-puma_tenis_corrida_masculino
        description: "Staging table with masculine running shoes from Puma"
        columns:
          - name: name
            description: "Shoes name"
          - name: price
            description: "Shoes price"
          - name: label
            description: "Shoes information (optional)"
          - name: last_sizes
            description: "Shoes last sizes"
          - name: datetime
            description: "The date and time when the crawler obtained the shoes information"