services:
  postgres:
    image: postgres:16
    container_name: db
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dbt-network

  dbt:
    build:
      context: ./
      dockerfile: Dockerfile.dbt
    container_name: dbt
    env_file:
      - ../datawarehouse/.env
    environment:
      DBT_PROFILES_DIR: /PROJECT/datawarehouse
      DBT_PROJECT_DIR: /PROJECT/datawarehouse
    volumes:
      - ../datawarehouse:/PROJECT/datawarehouse
      - ../include:/PROJECT/include
    ports:
    - "8080:8080"
    networks:
      - dbt-network
    depends_on:
      - postgres

  pgadmin:
    image: elestio/pgadmin:REL-8_12
    container_name: pgadmin_dbt
    restart: always
    env_file:
      - ../.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "5050:80"
    volumes:
    - pgadmin-cache:/var/lib/pgadmin
    networks:
      - dbt-network
    depends_on:
      - postgres

volumes:
  db-data:
    driver: local
  pgadmin-cache:
    driver: local

networks:
  dbt-network:
    driver: bridge