FROM python:3.12.7-slim as python-base
WORKDIR /

COPY ./api /api
COPY ./app /app
COPY ./datawarehouse /datawarehouse
COPY ./docker/execute.sh /

RUN pip install --upgrade pip && pip install -r /api/requirements.txt
