# name: Continuous Deployment

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# jobs:
#   dbt-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     # Baixa o repositório
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     # Configura o Docker Compose
#     - name: Set up Docker Compose
#       run: docker-compose -f docker-compose.yaml up -d

#     # Aguarda o banco de dados estar disponível
#     - name: Wait for Postgres
#       run: |
#         for i in {1..15}; do
#           if docker exec db pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}; then
#             echo "Postgres is ready!"
#             break
#           fi
#           echo "Waiting for Postgres..."
#           sleep 5
#         done

#     # Executa o dbt run no ambiente de produção
#     - name: Deploy dbt models to production
#       run: docker exec dbt dbt run --target prod

#     # Derruba os containers ao final
#     - name: Tear down Docker Compose
#       if: always()
#       run: docker-compose -f docker-compose.yaml down
